#!/bin/bash
# Update AWS Lambda and Google Cloud IP ranges in NGINX configuration
# Run this script periodically (e.g., via cron) to keep IP ranges up to date

set -e

# AWS IP ranges JSON file
AWS_IP_JSON="https://ip-ranges.amazonaws.com/ip-ranges.json"

# Google Cloud IP ranges JSON file
GCP_IP_JSON="https://www.gstatic.com/ipranges/cloud.json"

# Temporary files for downloaded JSON
TEMP_AWS_JSON="/tmp/aws-ip-ranges.json"
TEMP_GCP_JSON="/tmp/gcp-ip-ranges.json"

# Target NGINX config file (the map file)
NGINX_CONFIG="/etc/nginx/cloud-ips.map"

# Regions to include (Lambda-supported regions)
REGIONS=(
    "us-east-1"
    "us-east-2"
    "us-west-1"
    "us-west-2"
    "eu-west-1"
    "eu-central-1"
    "ap-southeast-1"
    "ap-southeast-2"
    "ap-northeast-1"
)

echo "Downloading AWS IP ranges..."
curl -s "$AWS_IP_JSON" -o "$TEMP_AWS_JSON"

echo "Downloading Google Cloud IP ranges..."
curl -s "$GCP_IP_JSON" -o "$TEMP_GCP_JSON"

echo "Generating new cloud-ips.map file..."

# Start building the new config file
cat > "$NGINX_CONFIG.new" << 'EOF'
# Cloud Provider IP Whitelist Map
# Auto-generated by update-cloud-ips.sh
#
# Update regularly:
# - AWS: https://ip-ranges.amazonaws.com/ip-ranges.json
# - Google Cloud: https://www.gstatic.com/ipranges/cloud.json
#
# Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

geo $cloud_allowed {
    default 0;
    
    # =============================================================================
    # AWS Lambda IP Ranges
    # =============================================================================
EOF

# Extract AWS Lambda IPs by region
for region in "${REGIONS[@]}"; do
    echo "    # $region" >> "$NGINX_CONFIG.new"
    jq -r --arg REGION "$region" \
        '.prefixes[] | select(.region==$REGION and .service=="AMAZON") | .ip_prefix' \
        "$TEMP_AWS_JSON" | sort -u | while read -r ip; do
        echo "    $ip 1;" >> "$NGINX_CONFIG.new"
    done
    echo "" >> "$NGINX_CONFIG.new"
done

# Add Google Cloud IPs
cat >> "$NGINX_CONFIG.new" << 'EOF'
    
    # =============================================================================
    # Google Cloud IP Ranges
    # =============================================================================
EOF

# Extract Google Cloud IPs (all prefixes)
jq -r '.prefixes[]? | select(.ipv4Prefix) | .ipv4Prefix' "$TEMP_GCP_JSON" | sort -u | while read -r ip; do
    echo "    $ip 1;" >> "$NGINX_CONFIG.new"
done

# Close the geo block
cat >> "$NGINX_CONFIG.new" << 'EOF'
    
    # Add your development/testing IP here
    # YOUR.DEV.IP.ADDRESS 1;
}
EOF

# Backup old config
if [ -f "$NGINX_CONFIG" ]; then
    cp "$NGINX_CONFIG" "$NGINX_CONFIG.bak"
    echo "Backed up old config to $NGINX_CONFIG.bak"
fi

# Move new config into place
mv "$NGINX_CONFIG.new" "$NGINX_CONFIG"

# Test NGINX configuration
echo "Testing NGINX configuration..."
if nginx -t; then
    echo "NGINX configuration is valid"
    echo "Reloading NGINX..."
    systemctl reload nginx
    echo "Done! IP ranges updated successfully."
else
    echo "ERROR: NGINX configuration test failed!"
    echo "Restoring backup..."
    mv "$NGINX_CONFIG.bak" "$NGINX_CONFIG"
    exit 1
fi

# Cleanup
rm -f "$TEMP_AWS_JSON" "$TEMP_GCP_JSON"
